package com.keygenqt.patterns.utils

const val PATTERN_ABSTRACT_FACTORY = "Abstract Factory"
const val PATTERN_ADAPTER = "Adapter"
const val PATTERN_BRIDGE = "Bridge"
const val PATTERN_BUILDER = "Builder"
const val PATTERN_CHAIN_OF_RESPONSIBILITY = "Chain of Responsibility"
const val PATTERN_COMMAND = "Command"
const val PATTERN_COMPOSITE = "Composite"
const val PATTERN_DECORATOR = "Decorator"
const val PATTERN_FACADE = "Facade"
const val PATTERN_FACTORY_METHOD = "Factory Method"
const val PATTERN_FLYWEIGHT = "Flyweight"
const val PATTERN_INTERPRETER = "Interpreter"
const val PATTERN_ITERATOR = "Iterator"
const val PATTERN_MEDIATOR = "Mediator"
const val PATTERN_MEMENTO = "Memento"
const val PATTERN_OBSERVER = "Observer"
const val PATTERN_PROTOTYPE = "Prototype"
const val PATTERN_PROXY = "Proxy"
const val PATTERN_SINGLETON = "Singleton"
const val PATTERN_STATE = "State"
const val PATTERN_STRATEGY = "Strategy"
const val PATTERN_TEMPLATE_METHOD = "Template Method"
const val PATTERN_VISITOR = "Visitor"